#!/usr/bin/env python3
"""
bundle.py – Bundle an OpenSCAD project into a single self-contained .scad file.

All `use <...>` and `include <...>` statements that reference files under the
repository root are inlined recursively.  Third-party library paths that cannot
be resolved are left as-is so the end-user can still install them separately.

Limitation
----------
The bundler inlines both `use` and `include` directives identically (full file
contents).  In OpenSCAD, `use` only imports modules/functions without executing
top-level code, whereas `include` executes everything.  Therefore, library files
referenced via `use` **must only contain module and function definitions** — no
top-level geometry, variable assignments, or other executable statements.  All
shared libraries in `libs/` follow this convention.

Usage
-----
    python scripts/bundle.py <main.scad> [-o <output.scad>] [-I <search_dir>] ...
                             [--exclude <prefix>] ...

Arguments
---------
    main.scad        Path to the top-level project file.
    -o, --output     Output file path.  Defaults to stdout.
    -I, --include    Additional search directories (may be repeated).
    --exclude        Path prefix to exclude from inlining (may be repeated).
                     Directives whose path starts with an excluded prefix are
                     kept as-is in the output so the end-user can provide the
                     library at render time.  Example: ``--exclude BOSL2``.
    --repo-root      Repository root directory.  Defaults to the directory
                     containing this script's parent.
"""

import argparse
import re
import sys
from pathlib import Path

# Regex matching `use <path>` or `include <path>` at the start of a line.
_DIRECTIVE = re.compile(
    r'^(?P<directive>use|include)\s*<(?P<path>[^>]+)>\s*;?\s*$',
    re.MULTILINE,
)

BUNDLE_HEADER = """\
// ============================================================
// AUTO-GENERATED – do not edit this file directly.
// Built by scripts/bundle.py from the source project.
// ============================================================

"""

SECTION_START = "// ---- begin: {path} ----\n"
SECTION_END   = "// ---- end:   {path} ----\n"


def resolve_path(ref_path: str, current_dir: Path, search_dirs: list[Path]) -> Path | None:
    """Return the absolute path of *ref_path* or None if it cannot be found."""
    candidate = (current_dir / ref_path).resolve()
    if candidate.is_file():
        return candidate
    for d in search_dirs:
        candidate = (d / ref_path).resolve()
        if candidate.is_file():
            return candidate
    return None


def _is_excluded(ref_path: str, exclude_prefixes: list[str]) -> bool:
    """Return True if *ref_path* starts with any of the excluded prefixes."""
    for prefix in exclude_prefixes:
        if ref_path == prefix or ref_path.startswith(prefix + "/"):
            return True
    return False


def bundle_file(
    file_path: Path,
    search_dirs: list[Path],
    visited: set[Path],
    exclude_prefixes: list[str] | None = None,
) -> str:
    """Recursively inline all resolvable use/include directives."""
    file_path = file_path.resolve()
    exclude_prefixes = exclude_prefixes or []

    if file_path in visited:
        # Already inlined – emit a comment instead of duplicating content.
        return f"// (already included: {file_path.name})\n"
    visited.add(file_path)

    try:
        source = file_path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"WARNING: cannot read {file_path}: {exc}", file=sys.stderr)
        return f"// WARNING: could not read {file_path}\n"

    lines = []
    cursor = 0

    for match in _DIRECTIVE.finditer(source):
        # Emit everything before this directive unchanged.
        lines.append(source[cursor : match.start()])

        ref_path = match.group("path")

        if _is_excluded(ref_path, exclude_prefixes):
            # Excluded library – keep the directive as-is for the end-user.
            lines.append(match.group(0) + "\n")
        else:
            resolved = resolve_path(ref_path, file_path.parent, search_dirs)

            if resolved is not None:
                lines.append(SECTION_START.format(path=resolved.name))
                lines.append(bundle_file(resolved, search_dirs, visited, exclude_prefixes))
                lines.append(SECTION_END.format(path=resolved.name))
            else:
                # Cannot resolve – keep original directive so downstream tooling
                # (e.g. OpenSCAD with MCAD installed) can still handle it.
                lines.append(match.group(0) + "\n")

        cursor = match.end()

    # Append any remaining content after the last directive.
    lines.append(source[cursor:])

    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Bundle an OpenSCAD project into a single .scad file."
    )
    parser.add_argument("input", help="Top-level .scad file to bundle.")
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output file path.  Omit or use '-' to write to stdout.",
    )
    parser.add_argument(
        "-I", "--include",
        action="append",
        dest="include_dirs",
        default=[],
        metavar="DIR",
        help="Additional search directory for includes (repeatable).",
    )
    parser.add_argument(
        "--repo-root",
        default=None,
        help=(
            "Repository root directory.  Defaults to two levels above this "
            "script (i.e. the repo root when the script lives in scripts/)."
        ),
    )
    parser.add_argument(
        "--exclude",
        action="append",
        dest="exclude_prefixes",
        default=[],
        metavar="PREFIX",
        help=(
            "Path prefix to exclude from inlining (repeatable).  Directives "
            "whose path starts with PREFIX are kept as-is.  "
            "Example: --exclude BOSL2"
        ),
    )

    args = parser.parse_args(argv)

    script_dir = Path(__file__).resolve().parent
    repo_root = Path(args.repo_root).resolve() if args.repo_root else script_dir.parent

    input_path = Path(args.input).resolve()
    if not input_path.is_file():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        return 1

    # Search order: file's own directory → repo libs/ → extra -I dirs → repo root
    search_dirs: list[Path] = [
        input_path.parent,
        repo_root / "libs",
        *[Path(d).resolve() for d in args.include_dirs],
        repo_root,
    ]

    visited: set[Path] = set()
    bundled = BUNDLE_HEADER + bundle_file(
        input_path, search_dirs, visited, args.exclude_prefixes,
    )

    if args.output and args.output != "-":
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(bundled, encoding="utf-8")
        print(f"Bundled {len(visited)} file(s) → {out_path}", file=sys.stderr)
    else:
        sys.stdout.write(bundled)

    return 0


if __name__ == "__main__":
    sys.exit(main())
